### ISSUE TITLE
Changement à réaliser

### ISSUE THREAD

**Issue by XdoctorwhoZ** [Panduza/panduza-cxx-platform#7]
- Le binaire ne doit plus s'appeler *Scan* mais *panduza-cxx-platform*
- Le script *compile.sh* doit être renommé en *start-platform.sh* et doit être mise au propre
- l'image docker doit être rendu public pour pouvoir être utiliser par n'importe qui (y compris moi)

**Comment by Valossy** [comment]
J'ai modifié le nom du binaire et le nom du script.

Par contre je ne peux pas modifier l'état de l'image docker, je ne peux pas le mettre en public de mon côté. Il est normalement modifiable dans l'onglet des packages

**Comment by XdoctorwhoZ** [comment]
C'est bon pour le coté public
